/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Ingredient = IDL.Record({
  'isGlutenFree' : IDL.Bool,
  'name' : IDL.Text,
  'isVegan' : IDL.Bool,
});
export const ProductTranslations = IDL.Record({
  'enDescription' : IDL.Text,
  'hiIngredients' : IDL.Vec(Ingredient),
  'hiName' : IDL.Text,
  'mlIngredients' : IDL.Vec(Ingredient),
  'taIngredients' : IDL.Vec(Ingredient),
  'taName' : IDL.Text,
  'hiDescription' : IDL.Text,
  'enIngredients' : IDL.Vec(Ingredient),
  'mlDescription' : IDL.Text,
  'taDescription' : IDL.Text,
  'enName' : IDL.Text,
  'mlName' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'sku' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'image' : ExternalBlob,
  'detailedDescription' : IDL.Text,
  'translations' : ProductTranslations,
  'priceInCents' : IDL.Nat,
});
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const FeedbackSubmission = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const GeneratedContent = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'contentType' : IDL.Text,
  'userId' : IDL.Nat,
  'createdAt' : IDL.Int,
});
export const IdeaSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const UserAccount = IDL.Record({
  'id' : IDL.Nat,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
});
export const AuthUserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const Cart = IDL.Record({
  'id' : IDL.Nat,
  'total' : IDL.Nat,
  'products' : IDL.Vec(IDL.Nat),
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'products' : IDL.Vec(Product),
  'customerEmail' : IDL.Text,
  'orderTimestamp' : IDL.Int,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCart' : IDL.Func([IDL.Vec(IDL.Nat), IDL.Nat], [IDL.Nat], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createGeneratedContent' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createOrder' : IDL.Func(
      [IDL.Vec(Product), IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createUserAccount' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAllFeedbacks' : IDL.Func([], [IDL.Vec(FeedbackSubmission)], ['query']),
  'getAllGeneratedContent' : IDL.Func(
      [],
      [IDL.Vec(GeneratedContent)],
      ['query'],
    ),
  'getAllIdeas' : IDL.Func([], [IDL.Vec(IdeaSubmission)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserAccount)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(AuthUserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([IDL.Nat], [IDL.Opt(Cart)], ['query']),
  'getContentByUserId' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(GeneratedContent)],
      ['query'],
    ),
  'getFeedbackById' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(FeedbackSubmission)],
      ['query'],
    ),
  'getGeneratedContentById' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(GeneratedContent)],
      ['query'],
    ),
  'getOrdersAll' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getPreferredLanguage' : IDL.Func([], [IDL.Text], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductsAll' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserAccountById' : IDL.Func([IDL.Nat], [IDL.Opt(UserAccount)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(AuthUserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([AuthUserProfile], [], []),
  'setPreferredLanguage' : IDL.Func([IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'submitFeedback' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitIdea' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [IDL.Nat],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateUserAccount' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Ingredient = IDL.Record({
    'isGlutenFree' : IDL.Bool,
    'name' : IDL.Text,
    'isVegan' : IDL.Bool,
  });
  const ProductTranslations = IDL.Record({
    'enDescription' : IDL.Text,
    'hiIngredients' : IDL.Vec(Ingredient),
    'hiName' : IDL.Text,
    'mlIngredients' : IDL.Vec(Ingredient),
    'taIngredients' : IDL.Vec(Ingredient),
    'taName' : IDL.Text,
    'hiDescription' : IDL.Text,
    'enIngredients' : IDL.Vec(Ingredient),
    'mlDescription' : IDL.Text,
    'taDescription' : IDL.Text,
    'enName' : IDL.Text,
    'mlName' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'sku' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'image' : ExternalBlob,
    'detailedDescription' : IDL.Text,
    'translations' : ProductTranslations,
    'priceInCents' : IDL.Nat,
  });
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const FeedbackSubmission = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const GeneratedContent = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'contentType' : IDL.Text,
    'userId' : IDL.Nat,
    'createdAt' : IDL.Int,
  });
  const IdeaSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const UserAccount = IDL.Record({
    'id' : IDL.Nat,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
  });
  const AuthUserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const Cart = IDL.Record({
    'id' : IDL.Nat,
    'total' : IDL.Nat,
    'products' : IDL.Vec(IDL.Nat),
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'products' : IDL.Vec(Product),
    'customerEmail' : IDL.Text,
    'orderTimestamp' : IDL.Int,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCart' : IDL.Func([IDL.Vec(IDL.Nat), IDL.Nat], [IDL.Nat], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createGeneratedContent' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createOrder' : IDL.Func(
        [IDL.Vec(Product), IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createUserAccount' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAllFeedbacks' : IDL.Func([], [IDL.Vec(FeedbackSubmission)], ['query']),
    'getAllGeneratedContent' : IDL.Func(
        [],
        [IDL.Vec(GeneratedContent)],
        ['query'],
      ),
    'getAllIdeas' : IDL.Func([], [IDL.Vec(IdeaSubmission)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserAccount)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(AuthUserProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([IDL.Nat], [IDL.Opt(Cart)], ['query']),
    'getContentByUserId' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(GeneratedContent)],
        ['query'],
      ),
    'getFeedbackById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(FeedbackSubmission)],
        ['query'],
      ),
    'getGeneratedContentById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(GeneratedContent)],
        ['query'],
      ),
    'getOrdersAll' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getPreferredLanguage' : IDL.Func([], [IDL.Text], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductsAll' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserAccountById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(UserAccount)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(AuthUserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([AuthUserProfile], [], []),
    'setPreferredLanguage' : IDL.Func([IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitFeedback' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitIdea' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [IDL.Nat],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateUserAccount' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };