/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuthUserProfile { 'name' : string, 'email' : string }
export interface Cart {
  'id' : bigint,
  'total' : bigint,
  'products' : Array<bigint>,
}
export interface ContactSubmission {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface FeedbackSubmission {
  'id' : bigint,
  'userId' : [] | [bigint],
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface GeneratedContent {
  'id' : bigint,
  'content' : string,
  'contentType' : string,
  'userId' : bigint,
  'createdAt' : bigint,
}
export interface IdeaSubmission {
  'id' : bigint,
  'name' : string,
  'email' : [] | [string],
  'message' : string,
  'timestamp' : bigint,
}
export interface Ingredient {
  'isGlutenFree' : boolean,
  'name' : string,
  'isVegan' : boolean,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'totalAmount' : bigint,
  'products' : Array<Product>,
  'customerEmail' : string,
  'orderTimestamp' : bigint,
}
export interface Product {
  'id' : bigint,
  'sku' : string,
  'isAvailable' : boolean,
  'image' : ExternalBlob,
  'detailedDescription' : string,
  'translations' : ProductTranslations,
  'priceInCents' : bigint,
}
export interface ProductTranslations {
  'enDescription' : string,
  'hiIngredients' : Array<Ingredient>,
  'hiName' : string,
  'mlIngredients' : Array<Ingredient>,
  'taIngredients' : Array<Ingredient>,
  'taName' : string,
  'hiDescription' : string,
  'enIngredients' : Array<Ingredient>,
  'mlDescription' : string,
  'taDescription' : string,
  'enName' : string,
  'mlName' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserAccount {
  'id' : bigint,
  'username' : string,
  'displayName' : string,
  'createdAt' : bigint,
  'isActive' : boolean,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCart' : ActorMethod<[Array<bigint>, bigint], bigint>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createGeneratedContent' : ActorMethod<[bigint, string, string], bigint>,
  'createOrder' : ActorMethod<[Array<Product>, bigint, string, string], bigint>,
  'createUserAccount' : ActorMethod<[string, string, string], bigint>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllFeedbacks' : ActorMethod<[], Array<FeedbackSubmission>>,
  'getAllGeneratedContent' : ActorMethod<[], Array<GeneratedContent>>,
  'getAllIdeas' : ActorMethod<[], Array<IdeaSubmission>>,
  'getAllUsers' : ActorMethod<[], Array<UserAccount>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [AuthUserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[bigint], [] | [Cart]>,
  'getContentByUserId' : ActorMethod<[bigint], Array<GeneratedContent>>,
  'getFeedbackById' : ActorMethod<[bigint], [] | [FeedbackSubmission]>,
  'getGeneratedContentById' : ActorMethod<[bigint], [] | [GeneratedContent]>,
  'getOrdersAll' : ActorMethod<[], Array<Order>>,
  'getPreferredLanguage' : ActorMethod<[], string>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProductsAll' : ActorMethod<[], Array<Product>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserAccountById' : ActorMethod<[bigint], [] | [UserAccount]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [AuthUserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[AuthUserProfile], undefined>,
  'setPreferredLanguage' : ActorMethod<[string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitContactForm' : ActorMethod<[string, string, string], bigint>,
  'submitFeedback' : ActorMethod<
    [[] | [bigint], string, string, string],
    bigint
  >,
  'submitIdea' : ActorMethod<[string, [] | [string], string], bigint>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateUserAccount' : ActorMethod<
    [bigint, string, string, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];